CREATE TABLE T_ORDER
(

    ID            INT PRIMARY KEY AUTO_INCREMENT,
    CONSUMER_ID   INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    ADDRESS       VARCHAR(100),
    ZIP_CODE      VARCHAR(100),
    DETAILS       VARCHAR(100),
    CREDIT_CARD   VARCHAR(100),
    END_DATE      VARCHAR(100),
    SECURITY_CODE VARCHAR(100)


);


CREATE TABLE T_ORDER_LINE_ITEM
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    MENU_ID  INT          NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    PRICE    DECIMAL      NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER (ID)
);

